from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
MAIN = (ROOT / 'app/src/main/java/com/example/flybrain/MainActivity.kt').read_text()
assert 'tarsalFoodContactIntensity(foodX, foodY)' in MAIN
assert 'FOOD_TARSAL_CONTACT_RADIUS' in MAIN
assert 'FOOD_GUSTATORY_SIGMA' in MAIN
# Gustatory input must not be generated by the old long-range Gaussian centered on the food.
assert 'stimulusIntensity(foodOn, foodX, foodY, .065f)' not in MAIN
# Long-range food signal remains exclusively olfactory.
assert 'injectOlfactoryPopulation(foodOn, foodX, foodY, FOOD_OLF_MAX_HZ)' in MAIN
# Contact/feeding must still be downstream of actual gustatory neural activity.
run_start = MAIN.index('private fun driveBody')
run_end = MAIN.index('\n        private fun runNeuralSimulation', run_start)
run = MAIN[run_start:run_end]
assert 'gustatoryRateNow = populationRate(GUST_START, GUST_END)' in run
assert 'if (foodContact && !foodContactLatched)' in run
print('TARSAL GUSTATION CONTACT AUDIT: PASS')
